---
- hosts: dev
  become: True
  tasks:
    - name: update repository
      apt:
       update_cache: true
       cache_valid_time: 3600
       force_apt_get: true
    - name: Install python pip
      apt:
       name: python3-pip
       state: present
    - name: Install Docker
      apt: 
       name: docker.io
       state: present
    - name: Start Docker
      service:
       state: started
       enabled: yes
       name: docker
    - name: Install docker-py
      pip:
        name: docker-py
    - name: Log into DockerHub
      docker_login:
        username: ghodkis
        password: {{password}}
    - name: Start the container
      docker_container:
         name: webapp
         image: "ghodkis/javamavenproject:1.0"
         state: started
         published_ports:
    - name: Log out of DockerHub
      docker_login:
        state: absent
        username: ghodkis
            - 0.0.0.0:8080:8080
