---
- hosts: dev
  become: True
  tasks:
    - name: update repository
      apt:
       update_cache: true
       cache_valid_time: 3600
       force_apt_get: true
    - name: Install python pip
      apt:
       name: python3-pip
       state: present
    - name: Install Docker
      apt: 
       name: docker
       state: present
    - name: Start Docker
      ansible.builtin.systemd:
       state: started
       daemon_reload: yes
       enabled: yes
       name: docker
    - name: Install docker-py python module
      apt:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
         name: webapp
         image: "ghodkis/javamavenproject:1.0"
         state: started
         published_ports:
            - 0.0.0.0:8080:8080
